#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformReportCSV.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JPstarter")]
	public partial class LINQtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKWPerformanceReport(KWPerformanceReport instance);
    partial void UpdateKWPerformanceReport(KWPerformanceReport instance);
    partial void DeleteKWPerformanceReport(KWPerformanceReport instance);
    #endregion
		
		public LINQtoSQLDataContext() : 
				base(global::PerformReportCSV.Properties.Settings.Default.JPstarterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KWPerformanceReport> KWPerformanceReports
		{
			get
			{
				return this.GetTable<KWPerformanceReport>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="staging.KWPerformanceReports")]
	public partial class KWPerformanceReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _channel;
		
		private string _day;
		
		private string _campaignid;
		
		private string _campaign;
		
		private string _campaignState;
		
		private string _adgroupid;
		
		private string _adGroup;
		
		private string _adGroupState;
		
		private string _keywordid;
		
		private string _keyword;
		
		private string _matchType;
		
		private string _firstpagecpc;
		
		private string _qualityscore;
		
		private string _maxcpc;
		
		private string _impressions;
		
		private string _searchimpressionshare;
		
		private string _clicks;
		
		private string _avgcpc;
		
		private string _cost;
		
		private string _avgposition;
		
		private string _finalurls;
		
		private string _importedat;
		
		private string _filename;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnchannelChanging(string value);
    partial void OnchannelChanged();
    partial void OndayChanging(string value);
    partial void OndayChanged();
    partial void OncampaignidChanging(string value);
    partial void OncampaignidChanged();
    partial void OncampaignChanging(string value);
    partial void OncampaignChanged();
    partial void OncampaignStateChanging(string value);
    partial void OncampaignStateChanged();
    partial void OnadgroupidChanging(string value);
    partial void OnadgroupidChanged();
    partial void OnadGroupChanging(string value);
    partial void OnadGroupChanged();
    partial void OnadGroupStateChanging(string value);
    partial void OnadGroupStateChanged();
    partial void OnkeywordidChanging(string value);
    partial void OnkeywordidChanged();
    partial void OnkeywordChanging(string value);
    partial void OnkeywordChanged();
    partial void OnmatchTypeChanging(string value);
    partial void OnmatchTypeChanged();
    partial void OnfirstpagecpcChanging(string value);
    partial void OnfirstpagecpcChanged();
    partial void OnqualityscoreChanging(string value);
    partial void OnqualityscoreChanged();
    partial void OnmaxcpcChanging(string value);
    partial void OnmaxcpcChanged();
    partial void OnimpressionsChanging(string value);
    partial void OnimpressionsChanged();
    partial void OnsearchimpressionshareChanging(string value);
    partial void OnsearchimpressionshareChanged();
    partial void OnclicksChanging(string value);
    partial void OnclicksChanged();
    partial void OnavgcpcChanging(string value);
    partial void OnavgcpcChanged();
    partial void OncostChanging(string value);
    partial void OncostChanged();
    partial void OnavgpositionChanging(string value);
    partial void OnavgpositionChanged();
    partial void OnfinalurlsChanging(string value);
    partial void OnfinalurlsChanged();
    partial void OnimportedatChanging(string value);
    partial void OnimportedatChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    #endregion
		
		public KWPerformanceReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channel", DbType="VarChar(50)")]
		public string channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				if ((this._channel != value))
				{
					this.OnchannelChanging(value);
					this.SendPropertyChanging();
					this._channel = value;
					this.SendPropertyChanged("channel");
					this.OnchannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day", DbType="VarChar(50)")]
		public string day
		{
			get
			{
				return this._day;
			}
			set
			{
				if ((this._day != value))
				{
					this.OndayChanging(value);
					this.SendPropertyChanging();
					this._day = value;
					this.SendPropertyChanged("day");
					this.OndayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaignid", DbType="VarChar(50)")]
		public string campaignid
		{
			get
			{
				return this._campaignid;
			}
			set
			{
				if ((this._campaignid != value))
				{
					this.OncampaignidChanging(value);
					this.SendPropertyChanging();
					this._campaignid = value;
					this.SendPropertyChanged("campaignid");
					this.OncampaignidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign", DbType="VarChar(50)")]
		public string campaign
		{
			get
			{
				return this._campaign;
			}
			set
			{
				if ((this._campaign != value))
				{
					this.OncampaignChanging(value);
					this.SendPropertyChanging();
					this._campaign = value;
					this.SendPropertyChanged("campaign");
					this.OncampaignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaignState", DbType="VarChar(50)")]
		public string campaignState
		{
			get
			{
				return this._campaignState;
			}
			set
			{
				if ((this._campaignState != value))
				{
					this.OncampaignStateChanging(value);
					this.SendPropertyChanging();
					this._campaignState = value;
					this.SendPropertyChanged("campaignState");
					this.OncampaignStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adgroupid", DbType="VarChar(50)")]
		public string adgroupid
		{
			get
			{
				return this._adgroupid;
			}
			set
			{
				if ((this._adgroupid != value))
				{
					this.OnadgroupidChanging(value);
					this.SendPropertyChanging();
					this._adgroupid = value;
					this.SendPropertyChanged("adgroupid");
					this.OnadgroupidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adGroup", DbType="VarChar(50)")]
		public string adGroup
		{
			get
			{
				return this._adGroup;
			}
			set
			{
				if ((this._adGroup != value))
				{
					this.OnadGroupChanging(value);
					this.SendPropertyChanging();
					this._adGroup = value;
					this.SendPropertyChanged("adGroup");
					this.OnadGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adGroupState", DbType="VarChar(50)")]
		public string adGroupState
		{
			get
			{
				return this._adGroupState;
			}
			set
			{
				if ((this._adGroupState != value))
				{
					this.OnadGroupStateChanging(value);
					this.SendPropertyChanging();
					this._adGroupState = value;
					this.SendPropertyChanged("adGroupState");
					this.OnadGroupStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywordid", DbType="VarChar(50)")]
		public string keywordid
		{
			get
			{
				return this._keywordid;
			}
			set
			{
				if ((this._keywordid != value))
				{
					this.OnkeywordidChanging(value);
					this.SendPropertyChanging();
					this._keywordid = value;
					this.SendPropertyChanged("keywordid");
					this.OnkeywordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="VarChar(50)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this.OnkeywordChanging(value);
					this.SendPropertyChanging();
					this._keyword = value;
					this.SendPropertyChanged("keyword");
					this.OnkeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matchType", DbType="VarChar(50)")]
		public string matchType
		{
			get
			{
				return this._matchType;
			}
			set
			{
				if ((this._matchType != value))
				{
					this.OnmatchTypeChanging(value);
					this.SendPropertyChanging();
					this._matchType = value;
					this.SendPropertyChanged("matchType");
					this.OnmatchTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstpagecpc", DbType="VarChar(50)")]
		public string firstpagecpc
		{
			get
			{
				return this._firstpagecpc;
			}
			set
			{
				if ((this._firstpagecpc != value))
				{
					this.OnfirstpagecpcChanging(value);
					this.SendPropertyChanging();
					this._firstpagecpc = value;
					this.SendPropertyChanged("firstpagecpc");
					this.OnfirstpagecpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualityscore", DbType="VarChar(50)")]
		public string qualityscore
		{
			get
			{
				return this._qualityscore;
			}
			set
			{
				if ((this._qualityscore != value))
				{
					this.OnqualityscoreChanging(value);
					this.SendPropertyChanging();
					this._qualityscore = value;
					this.SendPropertyChanged("qualityscore");
					this.OnqualityscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxcpc", DbType="VarChar(50)")]
		public string maxcpc
		{
			get
			{
				return this._maxcpc;
			}
			set
			{
				if ((this._maxcpc != value))
				{
					this.OnmaxcpcChanging(value);
					this.SendPropertyChanging();
					this._maxcpc = value;
					this.SendPropertyChanged("maxcpc");
					this.OnmaxcpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impressions", DbType="VarChar(50)")]
		public string impressions
		{
			get
			{
				return this._impressions;
			}
			set
			{
				if ((this._impressions != value))
				{
					this.OnimpressionsChanging(value);
					this.SendPropertyChanging();
					this._impressions = value;
					this.SendPropertyChanged("impressions");
					this.OnimpressionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchimpressionshare", DbType="VarChar(50)")]
		public string searchimpressionshare
		{
			get
			{
				return this._searchimpressionshare;
			}
			set
			{
				if ((this._searchimpressionshare != value))
				{
					this.OnsearchimpressionshareChanging(value);
					this.SendPropertyChanging();
					this._searchimpressionshare = value;
					this.SendPropertyChanged("searchimpressionshare");
					this.OnsearchimpressionshareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clicks", DbType="VarChar(50)")]
		public string clicks
		{
			get
			{
				return this._clicks;
			}
			set
			{
				if ((this._clicks != value))
				{
					this.OnclicksChanging(value);
					this.SendPropertyChanging();
					this._clicks = value;
					this.SendPropertyChanged("clicks");
					this.OnclicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avgcpc", DbType="VarChar(50)")]
		public string avgcpc
		{
			get
			{
				return this._avgcpc;
			}
			set
			{
				if ((this._avgcpc != value))
				{
					this.OnavgcpcChanging(value);
					this.SendPropertyChanging();
					this._avgcpc = value;
					this.SendPropertyChanged("avgcpc");
					this.OnavgcpcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost", DbType="VarChar(50)")]
		public string cost
		{
			get
			{
				return this._cost;
			}
			set
			{
				if ((this._cost != value))
				{
					this.OncostChanging(value);
					this.SendPropertyChanging();
					this._cost = value;
					this.SendPropertyChanged("cost");
					this.OncostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avgposition", DbType="VarChar(50)")]
		public string avgposition
		{
			get
			{
				return this._avgposition;
			}
			set
			{
				if ((this._avgposition != value))
				{
					this.OnavgpositionChanging(value);
					this.SendPropertyChanging();
					this._avgposition = value;
					this.SendPropertyChanged("avgposition");
					this.OnavgpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finalurls", DbType="VarChar(8000)")]
		public string finalurls
		{
			get
			{
				return this._finalurls;
			}
			set
			{
				if ((this._finalurls != value))
				{
					this.OnfinalurlsChanging(value);
					this.SendPropertyChanging();
					this._finalurls = value;
					this.SendPropertyChanged("finalurls");
					this.OnfinalurlsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_importedat", DbType="VarChar(50)")]
		public string importedat
		{
			get
			{
				return this._importedat;
			}
			set
			{
				if ((this._importedat != value))
				{
					this.OnimportedatChanging(value);
					this.SendPropertyChanging();
					this._importedat = value;
					this.SendPropertyChanged("importedat");
					this.OnimportedatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="VarChar(8000)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
