<?xml version="1.0" encoding="utf-8"?><Database Name="JPstarter" Class="LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=USER8450MT\SQLEXPRESS;Initial Catalog=JPstarter;Integrated Security=True" SettingsObjectName="PerformReportCSV.Properties.Settings" SettingsPropertyName="JPstarterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="staging.KWPerformanceReports" Member="KWPerformanceReports">
    <Type Name="KWPerformanceReport">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="channel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="day" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="campaignid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="campaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="campaignState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="adgroupid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="adGroup" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="adGroupState" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="keywordid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="matchType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="firstpagecpc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="qualityscore" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="maxcpc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="impressions" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="searchimpressionshare" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="clicks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="avgcpc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cost" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="avgposition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="finalurls" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="importedat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="filename" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>